Fix rake cucumber error and update gems.
The following error has occured when 'rake cucumber' was executed.

  undefined method `source_tag_names' for #<Cucumber::Ast::Scenario:0x007fbfe87455b8> (NoMethodError)
  /Users/kaz/.rvm/gems/ruby-1.9.2-p290@kakeibo3/gems/capybara-1.1.2/lib/capybara/cucumber.rb:18:in `Before'

The reason is that cucumber removed source_tag_names methods at version 1.1.5.
So, specified 'gem "cucumber", "=1.1.4"' in Gemfile and executed 'bundle update cucumber'.

And bundle update was executed and almost all gems has been updated.

fixed #4